name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $GITHUB_ENV
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV
        source $GITHUB_ENV

    - name: Set up Python 3.12.0
      run: |
        pyenv install 3.12.0
        pyenv global 3.12.0
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Run tests
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report
        
