version: 1.0
name: Qodana Analysis
on: [push, pull_request]
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0"
      - name: Install Qodana
        run: |
          wget https://data.services.jetbrains.com/products/download?code=QDP&platform=linux -O qodana-cli
          chmod +x qodana-cli
      - name: Run Qodana
        run: ./qodana-cli -d . -o qodana_report
      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: true # Enable the pull-request mode



